//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Scribble.rc
//
#define ID_VIEW_LAYERS                  1
#define IDR_MAINFRAME                   2
#define IDR_SCRIBTYPE                   3
#define ID_PALETTENORMAL                16
#define IDS_SCRIBBLE                    17
#define IDB_SCRIBBLE                    17
#define IDS_SCRIBBLE_PPG                18
#define IDS_SCRIBBLE_PPG_CAPTION        19
#define IDD_PROPPAGE_SCRIBBLE           19
#define IDB_BLUE_MARKER                 20
#define IDB_RED_MARKER                  21
#define IDB_GREEN_MARKER                22
#define IDB_BLACK_MARKER                23
#define IDB_ERASER                      24
#define IDB_CHANGE_WIDTH                25
#define ID_WIDTH_TWO                    26
#define ID_WIDTH_THREE                  27
#define ID_WIDTH_FIVE                   28
#define ID_WIDTH_EIGHT                  29
#define ID_VIEW_LAYERS2                 30
#define IDR_SCRIBTYPE2                  31
#define ID_VIEW_SCALETOFIT2             32
#define ID_VIEW_3D_XROTATION2           33
#define ID_VIEW_3D_YROTATION2           34
#define ID_VIEW_3D_ZROTATION2           35
#define ID_VIEW_3D_QROTATION2           36
#define ID_VIEW_3D_DEPTHOFFIELD2        37
#define ID_VIEW_3D_SETFOCUS2            38
#define ID_VIEW_3D_SOLIDS2              39
#define ID_VIEW_BACKGROUNDCOLOR2        40
#define ID_EDIT_CLEARALL2               41
#define ID_VIEW_TEXT2                   42
#define ID_VIEW_FONTCOLOR2              43
#define ID_VIEW_FONT2                   44
#define ID_VIEW_HOME2                   45
#define ID_FILE_NEWPARTNUMBER2          46
#define ID_VIEW_3D_SWITCHROTATIONSIGN2  47
#define ID_VIEW_3D_RENDERING_FULLWIREFRAME2 48
#define ID_VIEW_3D_RAYTRACEDIMAGE2      49
#define ID_VIEW_3D_FULLRENDERING2       50
#define ID_VIEW_3D_PARAMETERS2          51
#define IDD_ABOUTBOX                    100
#define IDD_PEN_WIDTHS                  101
#define IDC_AVAIL_MEM                   102
#define ID_MY_STATUS_BAR                103
#define IDD_ROTDEGREES                  104
#define IDD_DEPTHOFFIELD                105
#define IDC_THIN_PEN_WIDTH              106
#define IDD_FOCUS                       107
#define IDC_THICK_PEN_WIDTH             108
#define IDD_DIALOG1                     109
#define IDC_DEFAULT_PEN_WIDTHS          110
#define IDD_DIALOG2                     111
#define IDC_MATH_COPR                   112
#define IDC_EDIT1                       113
#define IDD_DIALOG3                     114
#define IDC_EDIT29                      114
#define IDC_DISK_SPACE                  115
#define IDC_EDIT30                      115
#define IDC_EDIT2                       116
#define IDC_EDIT31                      116
#define IDC_EDIT3                       117
#define IDC_EDIT32                      117
#define IDC_EDIT4                       118
#define IDC_EDIT33                      118
#define IDC_EDIT5                       119
#define IDC_EDIT34                      119
#define IDC_EDIT6                       120
#define IDI_ICON1                       121
#define IDC_EDIT25                      121
#define IDC_EDIT7                       122
#define IDC_EDIT26                      122
#define IDI_ICON2                       123
#define IDC_EDIT27                      123
#define IDC_EDIT8                       124
#define IDD_DIALOG4                     125
#define IDC_EDIT28                      125
#define IDC_EDIT9                       126
#define IDC_LIST1                       127
#define IDC_EDIT10                      128
#define IDD_DIALOG5                     129
#define IDC_CHECK1                      130
#define IDI_ICON3                       131
#define IDC_CHECK8                      131
#define IDC_CHECK2                      132
#define IDD_SPLASH                      133
#define IDC_CHECK9                      133
#define IDC_CHECK3                      134
#define IDI_ICON4                       135
#define IDC_CHECK10                     135
#define IDC_CHECK4                      136
#define IDB_PALETTE                     137
#define IDC_CHECK11                     137
#define IDC_CHECK5                      138
#define IDC_MAGNIFY                     139
#define IDC_CHECK12                     139
#define IDC_RADIO1                      140
#define IDC_CHECK6                      141
#define IDC_RADIO18                     141
#define IDC_PENCIL                      142
#define IDC_RADIO14                     142
#define IDC_RADIO19                     142
#define IDC_RADIO2                      143
#define IDC_EDIT11                      144
#define IDC_RADIO21                     144
#define IDC_GUNSIGHT                    145
#define IDC_RADIO15                     145
#define IDC_RADIO3                      146
#define IDC_EDIT12                      147
#define IDC_CURDEFAULT                  148
#define IDC_RADIO16                     148
#define IDC_SOBJECT                     149
#define IDC_RADIO17                     149
#define IDC_RADIO4                      150
#define IDC_CHECK13                     150
#define IDC_EDIT13                      151
#define IDC_CURPAINTCAN                 152
#define IDC_RADIO5                      153
#define IDC_EDIT14                      154
#define IDC_IBEAMCUR                    155
#define IDC_TYPEOB                      156
#define IDC_RADIO6                      157
#define IDC_EDIT15                      158
#define IDD_DIALOG6                     159
#define IDC_FORMULA                     160
#define IDC_RADIO7                      161
#define IDC_EDIT16                      162
#define IDD_DIALOG7                     163
#define IDC_LIST2                       164
#define IDC_RADIO8                      165
#define IDC_EDIT17                      166
#define IDC_RADIO9                      167
#define IDD_DIALOG8                     168
#define IDC_EDIT18                      169
#define IDC_RADIO10                     170
#define IDI_ICONSETUP                   171
#define IDC_EDIT19                      172
#define IDC_LIST4                       173
#define IDC_RADIO11                     174
#define IDD_DIALOG9                     175
#define IDC_EDIT20                      176
#define IDC_BUTTON1                     177
#define IDC_RADIO12                     178
#define IDI_ICON5                       179
#define IDC_EDIT21                      180
#define IDC_BUTTON2                     181
#define IDC_RADIO13                     182
#define IDC_EDIT22                      183
#define IDC_RADIO20                     183
#define IDD_DIALOG10                    184
#define IDC_BUTTON3                     184
#define IDC_CHECK7                      186
#define IDC_LIST3                       187
#define IDC_CHECK14                     187
#define IDD_DIALOG11                    188
#define IDC_EDIT23                      189
#define IDC_VARIABLE                    190
#define IDB_PALETTENS                   191
#define IDC_EDIT24                      192
#define IDD_DIALOG12                    193
#define IDC_BUTTON4                     194
#define IDD_DIALOG13                    195
#define IDC_STATICA1                    196
#define IDC_STATICA2                    197
#define IDD_DIALOG14                    198
#define IDC_STATICA3                    199
#define IDC_STATICA4                    200
#define IDC_STATICA5                    201
#define IDC_STATICA6                    202
#define IDC_STATICr                     203
#define IDC_STATICB1                    204
#define IDC_STATICg                     205
#define IDC_STATICB2                    206
#define IDC_STATICb                     207
#define IDC_STATICB3                    208
#define IDC_ATTHELP                     209
#define IDC_STATICB4                    210
#define IDC_STATICB5                    211
#define IDC_STATICB6                    212
#define IDC_INPBOXTITLE                 213
#define IDC_INPBOXTEXT                  214
#define IDC_EXPLAIN                     215
#define IDC_MINDEG                      216
#define ID_MENUBAR                      217
#define ID_PALETTEBAR                   218
#define ID_STATUSPANE0                  219
#define ID_STATUSPANE2                  220
#define IDC_CROSSX                      221
#define IDC_STATICFRAME1                221
#define ID_RFQ                          221
#define IDC_STATICFRMTOP                222
#define IDB_BITMAP1                     222
#define ID_INDICATOR_PROGRESS_PANE      222
#define IDD_DIALOG15                    223
#define IDD_DIALOG16                    224
#define IDI_ICON6                       226
#define IDC_OK                          227
#define IDD_DIALOG17                    227
#define IDR_WIDTH_MENU                  228
#define IDD_DIALOG18                    229
#define IDD_STEP                        229
#define IDC_STATICOBJECT                230
#define IDC_SLIDER1                     230
#define IDC_STATICOBJECT2               231
#define IDD_DIALOG19                    231
#define IDC_STATICIP                    233
#define IDC_STEP                        234
#define IDC_CSG                         235
#define IDC_DRAUGH                      236
#define IDC_FIRST_NAME                  237
#define IDC_LAST_NAME                   238
#define IDC_TOL                         239
#define IDC_TOLTEXT                     240
#define IDC_NAMETEXT                    241
#define IDC_MIDDLE_NAME                 242
#define IDC_ORGANIZATIONTEXT            243
#define IDC_ORGANIZATION                244
#define IDC_COMBOPREFIX                 245
#define IDC_COMBOSUFIX                  246
#define IDC_SHORTNAMES                  247
#define IDC_organizationStep            248
#define IDC_organizationLabelStep       249
#define IDC_organizationNameStep        250
#define IDC_organizationDescriptionStep 251
#define IDC_BIGICON                     1008
#define IDS_DISK_SPACE_UNAVAIL          1009
#define IDS_DISK_SPACE                  1010
#define IDS_MATH_COPR_NOTPRESENT        1011
#define IDS_MATH_COPR_PRESENT           1012
#define IDS_AVAIL_MEM                   1013
#define ID_PEN_THICK_OR_THIN            32768
#define ID_PEN_WIDTHS                   32769
#define ID_PEN_PENCOLOR                 32770
#define ID_VIEW_SCALETOFIT              32771
#define ID_VIEW_3D                      32773
#define ID_VIEW_3D_XROTATION            32774
#define ID_VIEW_3D_YROTATION            32775
#define ID_VIEW_3D_ZROTATION            32776
#define ID_VIEW_3D_QROTATION            32777
#define IDC_VIEW_3D_DEPTHOFFIELD        32778
#define ID_VIEW_3D_DEPTHOFFIELD         32779
#define ID_VIEW_3D_SETFOCUS             32780
#define ID_VIEW_3D_SOLIDS               32781
#define ID_VIEW_BACKGROUNDCOLOR         32782
#define ID_EDIT_CLEARALL                32784
#define ID_VIEW_TEXT                    32785
#define ID_VIEW_FONTCOLOR               32786
#define ID_VIEW_FONT                    32787
#define ID_VIEW_HOME                    32788
#define ID_FILE_NEWPARTNUMBER           32789
#define ID_VIEW_3D_SWITCHROTATIONSIGN   32790
#define ID_VIEW_3D_RENDERING_FULLWIREFRAME 32793
#define ID_VIEW_3D_RENDERING_CULLEDWIREFRAME 32794
#define ID_VIEW_3D_FULLRENDERING        32796
#define ID_VIEW_3D_PARAMETERS           32797
#define ID_VIEW_3D_SOLIDSOPAQUE         32798
#define ID_VIEW_3D_RAYTRACEDIMAGE       32799
#define ID_VIEW_2DSETUP                 32801
#define ID_EDIT_SKETCH                  32802
#define ID_VIEW_3D_CULLEDWIREFRAME      32803
#define ID_VIEW_3D_SOLIDWIREFRAME       32804
#define ID_VIEW_3D_SIMPLESHADEDSOLIDS   32805
#define ID_VIEW_3DIMAGE                 32806
#define ID_EDIT_SPECIALS                32807
#define ID_VIEW_DRAWINGSTATISTICS       32808
#define ID_EDIT_ZOOM                    32809
#define IDM_VIEW_PALETTE                32810
#define ID_EDIT_TEXTEDIT                32811
#define ID_EDIT_SURFACECOLORS           32812
#define ID_EDIT_NORMALMODE              32813
#define ID_VIEW_METRICDIMENSIONS        32814
#define ID_VIEW_FONTSANDCOLORS          32815
#define ID_VIEW_MODELS                  32816
#define ID_VIEW_WALLPAPER               32818
#define ID_VIEW_COLORSANDSTYLES_PENS_PENS 32820
#define ID_FILE_PASSWORD                32821
#define ID_EDIT_SELECT                  32822
#define ID_VIEW_INITIALDEFAULT          32823
#define ID_VIEW_WORKSPACE_SAVE          32825
#define ID_VIEW_WORKSPACE_LOAD          32826
#define ID_VIEW_DRAWING_STATISTICS      32827
#define ID_VIEW_COLORSANDSTYLES_CLINEPOLYSORT 32828

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        232
#define _APS_NEXT_COMMAND_VALUE         32829
#define _APS_NEXT_CONTROL_VALUE         250
#define _APS_NEXT_SYMED_VALUE           223
#endif
#endif
